#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

entry_points = """
[openmdao.parametric_geometry]
su2_mesh_component.comp.SU2MeshComp = su2_mesh_component.comp:SU2MeshComp

[openmdao.binpub]
su2_mesh_component.comp.MeshSender = su2_mesh_component.comp:MeshSender
"""

kwargs = {'author': '',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': '',
 'download_url': '',
 'include_package_data': True,
 'entry_points': entry_points,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': '',
 'maintainer': '',
 'maintainer_email': '',
 'name': 'su2_mesh_component',
 'package_data': {'su2_mesh_component': []},
 'package_dir': {'': 'src'},
 'packages': ['su2_mesh_component'],
 'url': '',
 'version': '0.1',
 'zip_safe': False}


setup(**kwargs)
